# Runs the unit tests
name: Docker build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker_build:
    runs-on: ubuntu-latest
    container: "docker:dind"
    steps:
      - uses: actions/checkout@v3
      - name: docker-build
        run: |
          docker login -u mmmtastymmm -p ${{ secrets.DOCKER_TOKEN }}
          docker build -f docker/gpt4all-j.Dockerfile -t mmmtastymmm/gtp4all-j:latest .
          docker push mmmtastymmm/gtp4all-j:latest
